linters:
  ColorVariable:
    enabled: false

  StringQuotes:
    enabled: true
    style: single_quotes

  UrlFormat:
    enabled: true

  SelectorDepth:
    enabled: true
    max_depth: 4

  PropertySortOrder:
    enabled: true
    order: recess

  NestingDepth:
    enabled: true
    max_depth: 5

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true
